### ISSUE TITLE
API key 문제(request for 403 error handling)

### ISSUE THREAD

**Issue by y-ngm-n** [nimod7890/commit-translator#1]
커밋 메시지 번역기가 출시되었다는 소식을 듣고 들뜬 마음에 실행해보았는데..

대뜸 API key를 요구하네요.. ㅜㅜ

입력하지 않으면 403 에러가 발생합니다.

너무 속상해서 일이 손에 잡히지 않습니다 제발 도와주세요..

<img width="983" alt="스크린샷 2023-12-03 오후 3 50 43" src="https://github.com/nimod7890/commit-translator/assets/68019733/160b35ba-de48-44f2-ab55-0e217e9bc362">

<img width="395" alt="스크린샷 2023-12-03 오후 3 53 42" src="https://github.com/nimod7890/commit-translator/assets/68019733/423dc3fc-7647-4762-9ba9-e47f25a24eda">

**Comment by nim-od** [comment]
벌써 이슈를 발견하셨다니 부지런하시군요. 
README.md에 작성해두었지만, deepl api key 받아서 입력하시면 403 없는 쾌적한 사용 가능합니다!

**Comment by nim-od** [comment]
참고로 403 error handling 처리는 다음 릴리즈에 포함될 예정입니다! 관심 갖고 기다려주세요~!

**Comment by nim-od** [comment]
api key 비어있는 케이스에 대해선 v1.1.0 에서 해결
invalid(unauthorized) key일 경우엔 추후 처리 필요
