### ISSUE TITLE
VScode marketplace 링크 추가

### ISSUE THREAD

**Issue by SeojinSeojin** [nimod7890/commit-translator#2]
리드미나 레포지토리 소개 링크에다가 브스코드 마켓플레이스로 가는 링크가 추가된다면
접근성이 좋아질 것 같습니다!!!!!!!!!

너무 멋집니다!!!!!!!!!!!!!

https://marketplace.visualstudio.com/items?itemName=nimod7890.commit-translator

**Comment by nim-od** [comment]
헉 따뜻한 지적 감사합니다! 바로 업데이트 하겠습니다!!
